name: $(BuildID)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - 'web/*'
      - 'auth/*'
      - 'backend/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from '/' root folder."
